name: getdealss
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.1.0
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.4.9
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^5.2.0+1
  firebase_auth: ^3.10.0
  firebase_core: ^1.23.0
  firebase_storage: ^10.3.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.12
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.4
  flutter_svg_provider: ^1.0.3
  flutterfire_ui: ^0.4.3+13
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  http: ^0.13.5
  image_picker: ^0.8.5+3
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  multi_select_flutter: ^4.1.2
  path_drawing: ^1.0.1
  restart_app: ^1.1.0+1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    # - images/a_dot_burr.jpeg
    - assets/
    - assets/lang/ar.json
    - assets/lang/en.json
    - assets/images/1x/
    - assets/images/1.5x/
    - assets/images/2x/
    - assets/images/3x/
    - assets/images/4x/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-regular.ttf
          style: normal
          weight: 400
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-regular.ttf
          style: "normal"
          weight: 400
        - asset: assets/fonts/Tajawal-500.ttf
          style: "normal"
          weight: 500
        - asset: assets/fonts/Tajawal-700.ttf
          style: "normal"
          weight: 700
        - asset: assets/fonts/Tajawal-300.ttf
          style: "normal"
          weight: 300
        - asset: assets/fonts/Tajawal-300.ttf
          style: "normal"
          weight: 300
    # - family:  Poppins
    #   fonts:
    #     - asset: "fonts/Poppins-regular.ttf"
    #       style: "normal"
    #       weight: 400
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
