// /// Flutter icons MyFlutterApp
// /// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
// /// This font was generated by FlutterIcon.com, which is derived from Fontello.
// ///
// /// To use this font, place it in your fonts/ directory and include the
// /// following in your pubspec.yaml
// ///
// /// flutter:
// ///   fonts:
// ///    - family:  MyFlutterApp
// ///      fonts:
// ///       - asset: fonts/MyFlutterApp.ttf
// ///
// /// 
// /// * Material Design Icons, Copyright (C) Google, Inc
// ///         Author:    Google
// ///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
// ///         Homepage:  https://design.google.com/icons/
// ///
// import 'package:flutter/widgets.dart';

// class MyFlutterApp {
//   MyFlutterApp._();

//   static const _kFontFam = 'MyFlutterApp';
//   static const String? _kFontPkg = null;

//   static const IconData notifications_active = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData filters1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData notifications_none = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData apple_pay_svgrepo_com__1_ = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData apple_pay_logo_svgrepo_com = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData apple_pay_svgrepo_com = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData credit_cards_svgrepo_com__3_ = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData credit_cards_svgrepo_com__2_ = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData credit_cards_svgrepo_com__1_ = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData credit_card_svgrepo_com = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData credit_cards_svgrepo_com = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData visa_svgrepo_com = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData visa_4_logo_svgrepo_com = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData visa_logo_svgrepo_com = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shopping_bag_svgrepo_com__3_ = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shopping_bag_svgrepo_com__2_ = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shopping_bag_svgrepo_com__1_ = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData shopping_bag_svgrepo_com = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData logout_svgrepo_com__2_ = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData logout_svgrepo_com__1_ = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData logout_svgrepo_com = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData exploration_tool_svgrepo_com = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData search_svgrepo_com = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData chat_text_svgrepo_com = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData notification_svgrepo_com = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData homepage_svgrepo_com = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData ring_notification_svgrepo_com = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData link_add_svgrepo_com = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData link_svgrepo_com__1_ = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData link_svgrepo_com = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData search_svgrepo_com__1_ = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData filters_2_svgrepo_com__1_ = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData vector = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData vector_1 = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
// }
